[package]
name = "dracut-install"
version = "0.1.0"
authors = ["Harald Hoyer <harald@redhat.com>"]
edition = "2018"

[dependencies]
getopts = "0"
byteorder = "1"
enum-primitive-derive = "0.1"
num-traits = "0.2.5"
bitflags = "1.0.0"
itertools = "0.7.8"
clap = "2.28.0"
