name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: install libkmod-dev iputils-ping
      run: sudo apt-get install libkmod-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
